config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  
  authenticated :user do
    root 'proyector#index'
    get 'registries/history', to: 'registries#history', as: 'history_registry'
    resources :registries
    get 'articles/:id', to: 'articles#index'
    resources :articles
    get 'articles/this/:id', to: 'articles#modify', as: 'edit_maintenance'
    get 'teachers/:id', to: 'teachers#index'
    resources :teachers
    get 'departments/:id', to: 'departments#index'
    resources :departments
    resources :classrooms
  end
  
  root 'home#index'
end

app/models/classroom.rb
# == Schema Information
#
# Table name: classrooms
#
#  id         :integer          not null, primary key
#  name       :string
#  status     :boolean          default(FALSE)
#  live       :boolean          default(TRUE)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Classroom < ApplicationRecord
    validates :name, presence: {message: "No debe dejar el campo de Salon en blanco."}, uniqueness: true
    
    before_create :modify_classroom
    before_save :modify_classroom

    def modify_classroom
        self.name = self.name.upcase
    end

end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
  def index
    @classroom = Classroom.all.where(live: true)
  end

  def show
    @classroom = Classroom.find(params[:id])
  end

  def new
    @classroom = Classroom.new
  end

  def edit
  end
  
  def create
    @finder = Classroom.find_by(name: classroom_params['name'].upcase)
    if Classroom.exists?(name: classroom_params['name'].upcase) && (@finder.live == false)
      Classroom.find_by(name: classroom_params['name'].upcase).update(live: true)
    else
      @classroom = Classroom.create(classroom_params)
      @classroom.name = classroom_params['name']
        if @classroom.save
          flash[:notice] = "Nuevo salón agregado."
        else
          @classroom.errors.each do |attr, msg|  
            flash[:alert] = msg
          end
        end
      end

    redirect_to classrooms_path
  end

  def update
    @classroom = Classroom.find(params[:id])

    if @classroom.update_attributes(classroom_params)
      flash[:notice] = "Los datos del salón se han actualizado."
      redirect_to classrooms_path
    else
      if @classroom.errors.any?  
        @classroom.errors.each do |attr, msg|  
          flash[:alert] = msg
        end 
      end
      redirect_to classroom_path
    end
  end

  def destroy
    @classroom = Classroom.find(params[:id])
    @classroom.live = false
    
    if @classroom.save
      flash[:notice] = "Se ha eliminado satisfactoriamente."
    end

    redirect_to classrooms_path
  end

private
  def classroom_params
    params.require(:classroom).permit(:name)
  end
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/views/classrooms/index.html.erb
<div class="grid-comp">
    <%= render 'layouts/headerDate' %>
    <%= render 'layouts/lateral' %>

    <div class="container main my-4">
    <div class="overflow o-100">
        <table class="table table-striped table-hover">
        <thead>
            <tr>
            <th scope="col">#</th>
            <th scope="col">Salon</th>
            <th scope="col">Eliminar</th>
            <th scope="col">Editar</th>
            </tr>
        </thead>
        <tbody>
            
            <% @classroom.each do |t| %>
            <tr>
            <th scope="row"><%= t.id %></th>
            <td><%= t.name %></td>
            <td>
            <%= link_to raw("<i class='btn btn-danger mi md-36 p-0' style='line-height:36px'>&#xE92B;</i>"), 
            t, method: :delete, 
            data: { confirm: 'Estas seguro de eliminarlo?' } %>
            </td>
            <td>
            <%= link_to raw("<i class='btn btn-warning mi md-36 md-light p-0' style='line-height:36px'>&#xE150;</i>"), classroom_path(t)%>
            </td>
            </tr>
            <% end %>

        </tbody>
        </table>
    </div>
    <%= link_to '+', new_classroom_path , class: "btn btn-success btn-lg btn-block d-flex justify-content-center font-weight-bold mt-1" %>
    </div>

    <%= render 'layouts/footer' %>
</div>

app/views/classrooms/new.html.erb
<div class="grid-comp">
    <%= render 'layouts/headerDate' %>
    <%= render 'layouts/lateral' %>

    <div class="container main my-5">

        <%= form_for @classroom, html: {class: "form"} do |f| %>
        <div class="form-group">
            <strong><%= f.label :name, "Nombre del salon: " %></strong>
            <%= f.text_field :name, class: "form-control",:autofocus => true %>
        </div>
        <%= f.submit "Guardar", class: "btn btn-success btn-lg btn-block" %>
        <% end %>
          
    </div>
    <%= render 'layouts/footer' %>
</div>

app/views/classrooms/show.html.erb
<div class="grid-comp">
    <%= render 'layouts/headerDate' %>
    <%= render 'layouts/lateral' %>

    <div class="container main my-5">

        <%= form_for @classroom, :method => :put, html: {class: "form"} do |f| %>
        <div class="form-group">
            <strong><%= f.label :name, "Nombre del salon: " %></strong>
            <%= f.text_field :name, class: "form-control",:autofocus => true %>
        </div>
        <%= f.submit "Guardar", class: "btn btn-success btn-lg btn-block" %>
        <% end %>
          
    </div>
    <%= render 'layouts/footer' %>
</div>