config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  
  authenticated :user do
    root 'proyector#index'
    get 'registries/history', to: 'registries#history', as: 'history_registry'
    resources :registries
    get 'articles/:id', to: 'articles#index'
    resources :articles
    get 'articles/this/:id', to: 'articles#modify', as: 'edit_maintenance'
    get 'teachers/:id', to: 'teachers#index'
    resources :teachers
    get 'departments/:id', to: 'departments#index'
    resources :departments
    resources :classrooms
  end
  
  root 'home#index'
end

app/models/article.rb
# == Schema Information
#
# Table name: articles
#
#  id          :integer          not null, primary key
#  name        :string
#  details     :string
#  description :text
#  service     :integer          default(0)
#  maintenance :datetime
#  status      :boolean          default(FALSE)
#  live        :boolean          default(TRUE)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Article < ApplicationRecord
    before_save :modify_article
    validates :name, :details, presence: true
    def modify_article
        self.name = self.name.capitalize
        self.details = self.details.upcase
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all.where(live: true).order('name ASC')
    @article = Article.new
    
    if params[:id]
      @article_find = Article.find(params[:id])
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def modify
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.create(article_params)
    
    if @article.save
      flash[:notice] = "Nuevo material registrado."
    else
      flash[:alert] = "Algo salio mal al guardar!"
    end

    redirect_to articles_path
  end

  def update
    @article_find = Article.find(params[:id])
    
    if @article_find.update_attributes(article_params)
      flash[:notice] = "Los datos del material se han actualizado."
    else
      flash[:alert] = "Algo salio mal al actualizar!"
    end

    redirect_to articles_path
  end
 
  def destroy
    @article = Article.find(params[:id])
    @article.update(live: false)
    
    
    flash[:notice] = "Se ha eliminado satisfactoriamente."
    

    redirect_to articles_path
  end

private
  def article_params
    params.require(:article).permit(:name, :details, :description, :status, :maintenance)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form_edit.html.erb
<!-- Modal Box-->

<div id="maintenance-modal" class="modal fade">
<!-- tabindex="-1" role="dialog" aria-labelledby="modalMaintenanceLabel" aria-hidden="true"> -->
<div class="modal-dialog"> <!-- role="document"> -->
    <div class="modal-content">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <h5 class="modal-title"><%= "title" %></h5>
        <span aria-hidden="true">&times;</span>
        </button>
    </div>

    
    <!--<%#= form_for :article, url: article_path(@article.id), method: :patch do |f| %>-->
        <div class="modal-body">
            <div class="form-group">
                <%#= f.label :maintenance, "Indique una fecha" %>
                <%#= f.text_field :maintenance, class: "datepicker-here form-control", autocomplete: "off", data: {language: 'es'}%>
            </div>
        </div>

    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>

        <%#= f.submit "Guardar", class: "btn btn-primary" %>        
    </div>
    <%# end %>
    </div>
</div>
</div>
<!-- Modal Box-->

app/views/articles/_update.html.erb
<%= form_for @article_find, url: {action: "update"} do |f| %>
    <div class="form-group">
        <%= f.label :name, "Nombre" %>
        <%= f.text_field :name, class: "form-control", value: @article_find.name %>
    </div>
    <div class="form-group">
        <%= f.label :details, "Marca y Modelo" %>
        <%= f.text_field :details, class: "form-control", value: @article_find.details %>
        <small class="text-muted">Ejemplo: Epson, V11H694020</small>
    </div>
    <div class="form-group">
        <%= f.label :description, "Descripcion" %>
        <%= f.text_area :description, class: "form-control", rows: 2, text: @article_find.description  %>
    </div>
    <div class="d-flex justify-content-around">
    <%= f.submit "Actualizar", class: "btn btn-success" %>
    <%= link_to "Regresar", articles_path, class: "btn btn-secondary" %>
    </div>
<% end %>

app/views/articles/index.html.erb
<div class="grid-comp">
<%= render 'layouts/headerDate' %>
<%= render 'layouts/lateral' %>
    <div class="container main">
        <br>
        <h1>Materiales</h1>

        <div class="row">
            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 my-2">
            
            <% if @article_find %>
            <!-- Form update-->
                <%= render 'articles/update' %>
            <!-- Form update-->
            <% else %>
            <!-- Form new -->
                <%= form_for(@article) do |f| %>
                <div class="form-group">
                    <%= f.label :name, "Nombre" %>
                    <%= f.text_field :name, class: "form-control", required: true %>
                </div>
                <div class="form-group">
                    <%= f.label :details, "Marca y modelo" %>
                    <%= f.text_field :details, class: "form-control", required: true %>
                    <small class="text-muted">Separe con una coma cada uno</small>
                </div>
                <div class="form-group">
                    <%= f.label :description, "Descripcion" %>
                    <%= f.text_area :description, class: "form-control", rows: 2 %>
                </div>
                <%= f.submit "Guardar", class: "btn btn-success" %>
                <% end %>
            <!-- Form new -->
            <% end %>
            </div>

            <!-- Cards Article -->
            <% @articles.each do |art| %>
                <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 my-2">
                    <div class="card border-success mb-3" style="max-width: 20rem;">
                    <div class="card-header bg-transparent border-success d-flex justify-content-between">
                        <div>
                            <%= art.name %>
                        </div>
                        <div>
                        <!-- edicion -->
                            <a href="/articles/<%= art.id %>" class="message edit px-2" data-toggle="tooltip" data-placement="top" title="Editar">
                                <i class="mi md-18">&#xE150;</i>
                            </a>
                            
                            <%= link_to raw("<i class='mi md-18 md-black'>&#xE92B;</i>"), art, 
                            method: :delete, 
                            data: { confirm: 'Estas seguro de eliminarlo?' }, 
                            class: "message destroy p-2",
                            "data-toggle" => "tooltip",
                            "data-placement" => "top",
                            :title => "Eliminar"%>
                        <!-- edicion -->
                        </div>
                    </div>
                    <div class="card-body text-success" style="position: relative">
                        <h4 class="card-title"><%= art.details %></h4>
                        <div class="card-text">
                                  
                            <span class="build message" data-toggle="tooltip" data-placement="top" title="Registrar Mantenimiento">
                                <%= link_to raw("<i class='mi'>&#xE869;</i>"), edit_maintenance_path(art.id), class: 'btn btn-outline-secondary' %>
                            </span>
                            
                            Mantenimiento: <br>
                            
                            <div style="text-indent: 1em">
                                <%= art.maintenance.nil? ? raw("<div class='text-danger'>>> No registrado</div>") : art.maintenance.strftime('%a, %d %b %Y') %> <br>
                            </div>
                            
                            En servicio: <br>
                            
                            <div style="text-indent: 1em">
                            
                            <% if art.service == 0 %>
                                <div class='text-danger'> >>Sin registrar<< </div>
                            <% else %>
                            <div class="text-primary">
                                <% if (art.service) < 86400 %>
                                    <%= Time.at(art.service).utc.strftime "%H:%M:%S" %>
                                <% else %>
                                    <%= Time.at(art.service).utc.strftime "#{(art.service / 86400).to_i} dia(s) %H:%M:%S" %>
                                <% end %>
                            </div>    
                            <% end %>
                            </div>

                        </div>
                    </div>
                    <div class="card-footer bg-transparent border-success text-muted text-truncate" 
                    style="height:80px; overflow-y:auto; white-space:normal">
                        <p><%= art.description %></p>
                    </div>
                    </div>
                </div>
            <% end %>
            <!-- Cards Article -->
            
        </div>
    </div>
    <%= render 'layouts/footer' %>
</div>

app/views/articles/modify.html.erb
<div class="grid-comp">
<%= render 'layouts/headerDate' %>
<%= render 'layouts/lateral' %>
    <div class="container main edit_article">
        <%= form_for @article, url: {action: "update"} do |f| %>
            <div class="form-group">
                <%= f.label :maintenance, "Indique una fecha" %>
                <%= f.text_field :maintenance, class: "date form-control", autocomplete: "off", value: @article.maintenance.nil? ? "" : (@article.maintenance).strftime('%d/%m/%Y')%>
            </div>
            <%= f.submit "Guardar", class: "btn btn-primary" %>        
        <% end %>
    </div>

    <%= render 'layouts/footer' %>
</div>