config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  
  authenticated :user do
    root 'proyector#index'
    get 'registries/history', to: 'registries#history', as: 'history_registry'
    resources :registries
    get 'articles/:id', to: 'articles#index'
    resources :articles
    get 'articles/this/:id', to: 'articles#modify', as: 'edit_maintenance'
    get 'teachers/:id', to: 'teachers#index'
    resources :teachers
    get 'departments/:id', to: 'departments#index'
    resources :departments
    resources :classrooms
  end
  
  root 'home#index'
end

app/views/layouts/_footer.html.erb
<footer class="footer d-flex px-4 justify-content-between">

        <%= link_to 'Cerrar Sesión', destroy_user_session_path, method: :delete, class: "btn btn-warning" %>

        <% if Registry.all.where(:status => true).count > 0 %>
        
                <div class="footer-access">
                        <%= link_to raw("<i class='mi md-28'>keyboard_arrow_right</i>Prestamo"),
                        new_registry_path, class: 'btn btn-primary mx-3' %>

                        <%= link_to raw("<i class='mi md-28'>access_alarm</i>Prestamos en curso"),
                        registries_path, class: "btn btn-warning mx-3" %>

                        <%= link_to raw("<i class='mi md-28'>equalizer</i>Registros"),
                        history_registry_path, class: "btn btn-danger" %>
                </div>

        <% end %>

</footer>

app/views/layouts/_headerDate.html.erb
<header class="cabecera row">
    <div class="col-xs-12 col-sm-2">
    <%= link_to image_tag("tecnm", style: "height: 70px"), root_path, class: 'h2 ml-4 c-link' %>    
    </div>
    <div class="clearfix hidden-sm-down col-md-6"></div>
    <div class="col-sm-3 col-md-2 date justify-content-center">
        <div class="d-flex flex-column">
            <span>Fecha: </span>
            <span class="date-text"><%= Time.now.strftime('%d/%m/%Y') %></span>
        </div>
    </div>
    <div class="col-sm-3 col-md-2 date justify-content-center">
        <div class="d-flex flex-column">
            <span>Hora: </span>
            <span id="date_time" class="date-text"></span>
        </div>
    </div>
</header>

app/views/layouts/_lateral.html.erb
<nav class="barra-lateral">
    <%= link_to teachers_path do %>
        <i class="mi md-36">person_pin</i>
        <small>Profesores</small>
    <% end %>
    <%= link_to departments_path do %>
        <i class="mi md-36">domain</i>
        <small>Departamentos</small>
    <% end %>
    <%= link_to articles_path do %>
        <i class="mi md-36">description</i>
        <small>Material</small>
    <% end %>
    <%= link_to classrooms_path do %>
        <i class="mi md-36">school</i>
        <small>Salones</small>
    <% end %>
    <%= link_to edit_user_registration_path do %>
        <i class="mi md-36">build</i>
        <small>Opciones</small>
    <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Proyector2</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Ubuntu&amp;subset=latin-ext" rel="stylesheet">
    <%= favicon_link_tag 'code.ico' %>
    <%= favicon_link_tag 'code.png', rel: 'apple-touch-icon', type: 'image/png' %>
  </head>

  <body>
    <% if notice %>
      <div class="notice"><i class="mi md-36">&#xE2BD;</i><span style="margin-left: 10px; position: relative; top: -10px;"><%= notice %></span></div>
    <% elsif alert %>
      <div class="alert-rails"><i class="mi md-36">&#xE000;</i><span style="margin-left: 10px; position: relative; top: -10px;"><%= alert %></span></div>
    <% end %>

    <%= yield %>
  </body>
</html>